[package]
name = "feathers-and-glass"
version = "0.1.0"
authors = ["Jack Kellenberger"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = { version = "0.8.7" }